version: '3.1'

# Refs https://qiita.com/iedred7584/items/76095f9a3bed68e11233

services:

  # https://hub.docker.com/_/postgres
  postgres_db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db_1
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 15432:5432

  # https://hub.docker.com/_/adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 9380:8080
      # http://localhost:9380/
